name = "LinearNovelty"
uuid = "973bbfaa-2ec3-4c90-b669-2981635c6b1a"
authors = ["Adam Ulrich <adamo.ulrich@gmail.com> and contributors"]
version = "1.0.0-DEV"

[deps]
HiGHS = "87dc4568-4c63-4d18-b0c0-bb2238e4078b"
JuMP = "4076af6c-e467-56ae-b986-b466b2749572"
Lazy = "50d2b5c4-7a5e-59d5-8109-a42b560f39c0"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"

[compat]
HiGHS = "1"
JuMP = "1"
Lazy = "0.15"
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
